coverage:
  precision: 2 # 2 = xx.xx%, 0 = xx%
  round: down # down|up|nearest
  range: 40...70 # default 70...90, red...green

  status:
    project: # measuring the overall project coverage
      default: # context, you can create multiple ones with custom titles
        enabled: yes # must be yes|true to enable this status
        threshold: 5 # allowed to drop X% and still result in a "success" commit status

    #Not interesting at the moment
    patch: off # measures lines adjusted in the pull request or single commit, if the commit is not in a pull request.
