git:
  commitMessage: "chore(release): v${version}"
  tagAnnotation: "chore(release): v${version}"
  tagName: "v${version}"

hooks:
  after:bump: 
    - "npm run changelog:update"
    - "npm run organize"

npm:
  publish: false
  private: true
  registry: "OMITTED"
