version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "@types/vscode"
    automerged_updates:
      - match:
          dependency_type: "all"
